### ISSUE TITLE
About missing files of mnist and fashion-mnist datasets

### ISSUE THREAD

**Issue by jiyuwangbupt** [PGelss/scikit_tt#14]
Dear Dr. Gelß,
Thanks a lot for this awesome library, I am a novice in this field! When I use the Kernel-based MANDy to perform  MNIST image classification in mnist.py,  I found no mnist reduced, mnist reduced
fmnist_full, mnist reduced these four data files, can you please send me a copy or add it to your library? My email is jiyuwang@bupt.edu.cn.

Thanks a lot
Best!

**Comment by PGelss** [comment]
Hello,

thank you for your interest in our toolbox. I sent you a link via email.

Best regards,
Patrick

**Comment by SaeedPourjafar** [comment]
Hello Dr.  Gelß,
I'm a data science student and I'm also interested in having those four datasets to know more about tensor and TT formats in general. I appreciate it if you send me a link as well. Here's my email:
m.pourjafar@student.uw.edu.pl
Kind regards,
Mohammad Saeed
