### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by PGelss** [PGelss/scikit_tt#6]
replace @-operators

**Comment by marscher** [comment]
On 18.01.19 16:21, Patrick Gelß wrote:
> replace @-operators
>
You (or I) can write a regular expression doing the replacement for all files in one command :)

It will grant you Python2 compatibility for almost no effort.

**Comment by PGelss** [comment]
- added alias function (``TT.dot(t,u)``) for @-operator
- replaced ``a/b`` by ``np.true_divide(a,b)``
